/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.fm.domain.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.setOrThrow;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFInvoice extends VertxPojo, Serializable {

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.KEY</code>. 「key」- 发票主键
     */
    public IFInvoice setKey(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.KEY</code>. 「key」- 发票主键
     */
    public String getKey();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.NAME</code>. 「name」- 发票名称
     */
    public IFInvoice setName(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.NAME</code>. 「name」- 发票名称
     */
    public String getName();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.CODE</code>. 「code」- 发票机器码
     */
    public IFInvoice setCode(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.CODE</code>. 「code」- 发票机器码
     */
    public String getCode();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.TYPE</code>. 「type」- 发票类型
     */
    public IFInvoice setType(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.TYPE</code>. 「type」- 发票类型
     */
    public String getType();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.AMOUNT</code>. 「amount」- 发票金额
     */
    public IFInvoice setAmount(BigDecimal value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.AMOUNT</code>. 「amount」- 发票金额
     */
    public BigDecimal getAmount();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.COMMENT</code>. 「comment」 - 发票备注
     */
    public IFInvoice setComment(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.COMMENT</code>. 「comment」 - 发票备注
     */
    public String getComment();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.INVOICE_TITLE</code>.
     * 「invoiceTitle」- 发票抬头
     */
    public IFInvoice setInvoiceTitle(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.INVOICE_TITLE</code>.
     * 「invoiceTitle」- 发票抬头
     */
    public String getInvoiceTitle();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.INVOICE_NUMBER</code>.
     * 「invoiceNumber」- 发票代码
     */
    public IFInvoice setInvoiceNumber(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.INVOICE_NUMBER</code>.
     * 「invoiceNumber」- 发票代码
     */
    public String getInvoiceNumber();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.INVOICE_SERIAL</code>.
     * 「invoiceSerial」- 发票号码
     */
    public IFInvoice setInvoiceSerial(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.INVOICE_SERIAL</code>.
     * 「invoiceSerial」- 发票号码
     */
    public String getInvoiceSerial();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.TIN</code>. 「tin」- 税号：纳税人识别号
     */
    public IFInvoice setTin(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.TIN</code>. 「tin」- 税号：纳税人识别号
     */
    public String getTin();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.TIN_NAME</code>. 「tinName」- 纳税人姓名
     */
    public IFInvoice setTinName(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.TIN_NAME</code>. 「tinName」- 纳税人姓名
     */
    public String getTinName();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.PERSONAL</code>. 「personal」- 是否个人发票
     */
    public IFInvoice setPersonal(Boolean value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.PERSONAL</code>. 「personal」- 是否个人发票
     */
    public Boolean getPersonal();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.DESC_BANK</code>. 「descBank」- 开户行信息
     */
    public IFInvoice setDescBank(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.DESC_BANK</code>. 「descBank」- 开户行信息
     */
    public String getDescBank();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.DESC_COMPANY</code>. 「descCompany」-
     * 公司信息
     */
    public IFInvoice setDescCompany(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.DESC_COMPANY</code>. 「descCompany」-
     * 公司信息
     */
    public String getDescCompany();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.DESC_LOCATION</code>.
     * 「descLocation」- 地址电话
     */
    public IFInvoice setDescLocation(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.DESC_LOCATION</code>.
     * 「descLocation」- 地址电话
     */
    public String getDescLocation();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.DESC_USER</code>. 「descUser」-
     * 个人发票用户信息
     */
    public IFInvoice setDescUser(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.DESC_USER</code>. 「descUser」-
     * 个人发票用户信息
     */
    public String getDescUser();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.NAME_RECEIPT</code>.
     * 「nameReceipt」收款人
     */
    public IFInvoice setNameReceipt(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.NAME_RECEIPT</code>.
     * 「nameReceipt」收款人
     */
    public String getNameReceipt();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.NAME_RECHECK</code>.
     * 「nameRecheck」复核人
     */
    public IFInvoice setNameRecheck(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.NAME_RECHECK</code>.
     * 「nameRecheck」复核人
     */
    public String getNameRecheck();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.NAME_BILLING</code>.
     * 「nameBilling」开票人
     */
    public IFInvoice setNameBilling(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.NAME_BILLING</code>.
     * 「nameBilling」开票人
     */
    public String getNameBilling();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.NAME_SELLING</code>.
     * 「nameSelling」销售人
     */
    public IFInvoice setNameSelling(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.NAME_SELLING</code>.
     * 「nameSelling」销售人
     */
    public String getNameSelling();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.ORDER_ID</code>. 「orderId」-
     * 订单对应的订单ID
     */
    public IFInvoice setOrderId(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.ORDER_ID</code>. 「orderId」-
     * 订单对应的订单ID
     */
    public String getOrderId();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.SIGMA</code>. 「sigma」- 统一标识
     */
    public IFInvoice setSigma(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.SIGMA</code>. 「sigma」- 统一标识
     */
    public String getSigma();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.LANGUAGE</code>. 「language」- 使用的语言
     */
    public IFInvoice setLanguage(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.LANGUAGE</code>. 「language」- 使用的语言
     */
    public String getLanguage();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.ACTIVE</code>. 「active」- 是否启用
     */
    public IFInvoice setActive(Boolean value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.ACTIVE</code>. 「active」- 是否启用
     */
    public Boolean getActive();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.METADATA</code>. 「metadata」- 附加配置数据
     */
    public IFInvoice setMetadata(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.METADATA</code>. 「metadata」- 附加配置数据
     */
    public String getMetadata();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.CREATED_AT</code>. 「createdAt」-
     * 创建时间
     */
    public IFInvoice setCreatedAt(LocalDateTime value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.CREATED_AT</code>. 「createdAt」-
     * 创建时间
     */
    public LocalDateTime getCreatedAt();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.CREATED_BY</code>. 「createdBy」- 创建人
     */
    public IFInvoice setCreatedBy(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.CREATED_BY</code>. 「createdBy」- 创建人
     */
    public String getCreatedBy();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.UPDATED_AT</code>. 「updatedAt」-
     * 更新时间
     */
    public IFInvoice setUpdatedAt(LocalDateTime value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.UPDATED_AT</code>. 「updatedAt」-
     * 更新时间
     */
    public LocalDateTime getUpdatedAt();

    /**
     * Setter for <code>DB_ETERNAL.F_INVOICE.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    public IFInvoice setUpdatedBy(String value);

    /**
     * Getter for <code>DB_ETERNAL.F_INVOICE.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    public String getUpdatedBy();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IFInvoice
     */
    public void from(IFInvoice from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IFInvoice
     */
    public <E extends IFInvoice> E into(E into);

        @Override
        public default IFInvoice fromJson(io.vertx.core.json.JsonObject json) {
                setOrThrow(this::setKey,json::getString,"KEY","java.lang.String");
                setOrThrow(this::setName,json::getString,"NAME","java.lang.String");
                setOrThrow(this::setCode,json::getString,"CODE","java.lang.String");
                setOrThrow(this::setType,json::getString,"TYPE","java.lang.String");
                setOrThrow(this::setAmount,key -> {String s = json.getString(key); return s==null?null:new java.math.BigDecimal(s);},"AMOUNT","java.math.BigDecimal");
                setOrThrow(this::setComment,json::getString,"COMMENT","java.lang.String");
                setOrThrow(this::setInvoiceTitle,json::getString,"INVOICE_TITLE","java.lang.String");
                setOrThrow(this::setInvoiceNumber,json::getString,"INVOICE_NUMBER","java.lang.String");
                setOrThrow(this::setInvoiceSerial,json::getString,"INVOICE_SERIAL","java.lang.String");
                setOrThrow(this::setTin,json::getString,"TIN","java.lang.String");
                setOrThrow(this::setTinName,json::getString,"TIN_NAME","java.lang.String");
                setOrThrow(this::setPersonal,json::getBoolean,"PERSONAL","java.lang.Boolean");
                setOrThrow(this::setDescBank,json::getString,"DESC_BANK","java.lang.String");
                setOrThrow(this::setDescCompany,json::getString,"DESC_COMPANY","java.lang.String");
                setOrThrow(this::setDescLocation,json::getString,"DESC_LOCATION","java.lang.String");
                setOrThrow(this::setDescUser,json::getString,"DESC_USER","java.lang.String");
                setOrThrow(this::setNameReceipt,json::getString,"NAME_RECEIPT","java.lang.String");
                setOrThrow(this::setNameRecheck,json::getString,"NAME_RECHECK","java.lang.String");
                setOrThrow(this::setNameBilling,json::getString,"NAME_BILLING","java.lang.String");
                setOrThrow(this::setNameSelling,json::getString,"NAME_SELLING","java.lang.String");
                setOrThrow(this::setOrderId,json::getString,"ORDER_ID","java.lang.String");
                setOrThrow(this::setSigma,json::getString,"SIGMA","java.lang.String");
                setOrThrow(this::setLanguage,json::getString,"LANGUAGE","java.lang.String");
                setOrThrow(this::setActive,json::getBoolean,"ACTIVE","java.lang.Boolean");
                setOrThrow(this::setMetadata,json::getString,"METADATA","java.lang.String");
                setOrThrow(this::setCreatedAt,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"CREATED_AT","java.time.LocalDateTime");
                setOrThrow(this::setCreatedBy,json::getString,"CREATED_BY","java.lang.String");
                setOrThrow(this::setUpdatedAt,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"UPDATED_AT","java.time.LocalDateTime");
                setOrThrow(this::setUpdatedBy,json::getString,"UPDATED_BY","java.lang.String");
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                json.put("KEY",getKey());
                json.put("NAME",getName());
                json.put("CODE",getCode());
                json.put("TYPE",getType());
                json.put("AMOUNT",getAmount()==null?null:getAmount().toString());
                json.put("COMMENT",getComment());
                json.put("INVOICE_TITLE",getInvoiceTitle());
                json.put("INVOICE_NUMBER",getInvoiceNumber());
                json.put("INVOICE_SERIAL",getInvoiceSerial());
                json.put("TIN",getTin());
                json.put("TIN_NAME",getTinName());
                json.put("PERSONAL",getPersonal());
                json.put("DESC_BANK",getDescBank());
                json.put("DESC_COMPANY",getDescCompany());
                json.put("DESC_LOCATION",getDescLocation());
                json.put("DESC_USER",getDescUser());
                json.put("NAME_RECEIPT",getNameReceipt());
                json.put("NAME_RECHECK",getNameRecheck());
                json.put("NAME_BILLING",getNameBilling());
                json.put("NAME_SELLING",getNameSelling());
                json.put("ORDER_ID",getOrderId());
                json.put("SIGMA",getSigma());
                json.put("LANGUAGE",getLanguage());
                json.put("ACTIVE",getActive());
                json.put("METADATA",getMetadata());
                json.put("CREATED_AT",getCreatedAt()==null?null:getCreatedAt().toString());
                json.put("CREATED_BY",getCreatedBy());
                json.put("UPDATED_AT",getUpdatedAt()==null?null:getUpdatedAt().toString());
                json.put("UPDATED_BY",getUpdatedBy());
                return json;
        }

}
