/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.lbs.domain.tables.records;


import cn.vertxup.lbs.domain.tables.LTent;
import cn.vertxup.lbs.domain.tables.interfaces.ILTent;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LTentRecord extends UpdatableRecordImpl<LTentRecord> implements VertxPojo, Record16<String, String, String, String, String, String, Integer, String, String, Boolean, String, String, LocalDateTime, String, LocalDateTime, String>, ILTent {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.KEY</code>. 「key」- 主键
     */
    @Override
    public LTentRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.KEY</code>. 「key」- 主键
     */
    @Override
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.NAME</code>. 「name」- 名称
     */
    @Override
    public LTentRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.NAME</code>. 「name」- 名称
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.CODE</code>. 「code」- 编码
     */
    @Override
    public LTentRecord setCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.CODE</code>. 「code」- 编码
     */
    @Override
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.CONTACT_PHONE</code>. 「contactPhone」-
     * 联系电话
     */
    @Override
    public LTentRecord setContactPhone(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.CONTACT_PHONE</code>. 「contactPhone」-
     * 联系电话
     */
    @Override
    public String getContactPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.CONTACT_NAME</code>. 「contactName」-
     * 联系人姓名
     */
    @Override
    public LTentRecord setContactName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.CONTACT_NAME</code>. 「contactName」-
     * 联系人姓名
     */
    @Override
    public String getContactName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.METADATA</code>. 「metadata」- 附加配置
     */
    @Override
    public LTentRecord setMetadata(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.METADATA</code>. 「metadata」- 附加配置
     */
    @Override
    public String getMetadata() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.ORDER</code>. 「order」- 排序
     */
    @Override
    public LTentRecord setOrder(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.ORDER</code>. 「order」- 排序
     */
    @Override
    public Integer getOrder() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.LOCATION_ID</code>. 「locationId」-
     * 关联地址ID
     */
    @Override
    public LTentRecord setLocationId(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.LOCATION_ID</code>. 「locationId」-
     * 关联地址ID
     */
    @Override
    public String getLocationId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.YARD_ID</code>. 「yardId」- 关联小区ID
     */
    @Override
    public LTentRecord setYardId(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.YARD_ID</code>. 「yardId」- 关联小区ID
     */
    @Override
    public String getYardId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public LTentRecord setActive(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.SIGMA</code>. 「sigma」- 统一标识
     */
    @Override
    public LTentRecord setSigma(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.SIGMA</code>. 「sigma」- 统一标识
     */
    @Override
    public String getSigma() {
        return (String) get(10);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public LTentRecord setLanguage(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public String getLanguage() {
        return (String) get(11);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LTentRecord setCreatedAt(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public LTentRecord setCreatedBy(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LTentRecord setUpdatedAt(LocalDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>DB_ETERNAL.L_TENT.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public LTentRecord setUpdatedBy(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_TENT.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<String, String, String, String, String, String, Integer, String, String, Boolean, String, String, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<String, String, String, String, String, String, Integer, String, String, Boolean, String, String, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return LTent.L_TENT.KEY;
    }

    @Override
    public Field<String> field2() {
        return LTent.L_TENT.NAME;
    }

    @Override
    public Field<String> field3() {
        return LTent.L_TENT.CODE;
    }

    @Override
    public Field<String> field4() {
        return LTent.L_TENT.CONTACT_PHONE;
    }

    @Override
    public Field<String> field5() {
        return LTent.L_TENT.CONTACT_NAME;
    }

    @Override
    public Field<String> field6() {
        return LTent.L_TENT.METADATA;
    }

    @Override
    public Field<Integer> field7() {
        return LTent.L_TENT.ORDER;
    }

    @Override
    public Field<String> field8() {
        return LTent.L_TENT.LOCATION_ID;
    }

    @Override
    public Field<String> field9() {
        return LTent.L_TENT.YARD_ID;
    }

    @Override
    public Field<Boolean> field10() {
        return LTent.L_TENT.ACTIVE;
    }

    @Override
    public Field<String> field11() {
        return LTent.L_TENT.SIGMA;
    }

    @Override
    public Field<String> field12() {
        return LTent.L_TENT.LANGUAGE;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return LTent.L_TENT.CREATED_AT;
    }

    @Override
    public Field<String> field14() {
        return LTent.L_TENT.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return LTent.L_TENT.UPDATED_AT;
    }

    @Override
    public Field<String> field16() {
        return LTent.L_TENT.UPDATED_BY;
    }

    @Override
    public String component1() {
        return getKey();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getCode();
    }

    @Override
    public String component4() {
        return getContactPhone();
    }

    @Override
    public String component5() {
        return getContactName();
    }

    @Override
    public String component6() {
        return getMetadata();
    }

    @Override
    public Integer component7() {
        return getOrder();
    }

    @Override
    public String component8() {
        return getLocationId();
    }

    @Override
    public String component9() {
        return getYardId();
    }

    @Override
    public Boolean component10() {
        return getActive();
    }

    @Override
    public String component11() {
        return getSigma();
    }

    @Override
    public String component12() {
        return getLanguage();
    }

    @Override
    public LocalDateTime component13() {
        return getCreatedAt();
    }

    @Override
    public String component14() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component15() {
        return getUpdatedAt();
    }

    @Override
    public String component16() {
        return getUpdatedBy();
    }

    @Override
    public String value1() {
        return getKey();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getCode();
    }

    @Override
    public String value4() {
        return getContactPhone();
    }

    @Override
    public String value5() {
        return getContactName();
    }

    @Override
    public String value6() {
        return getMetadata();
    }

    @Override
    public Integer value7() {
        return getOrder();
    }

    @Override
    public String value8() {
        return getLocationId();
    }

    @Override
    public String value9() {
        return getYardId();
    }

    @Override
    public Boolean value10() {
        return getActive();
    }

    @Override
    public String value11() {
        return getSigma();
    }

    @Override
    public String value12() {
        return getLanguage();
    }

    @Override
    public LocalDateTime value13() {
        return getCreatedAt();
    }

    @Override
    public String value14() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value15() {
        return getUpdatedAt();
    }

    @Override
    public String value16() {
        return getUpdatedBy();
    }

    @Override
    public LTentRecord value1(String value) {
        setKey(value);
        return this;
    }

    @Override
    public LTentRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public LTentRecord value3(String value) {
        setCode(value);
        return this;
    }

    @Override
    public LTentRecord value4(String value) {
        setContactPhone(value);
        return this;
    }

    @Override
    public LTentRecord value5(String value) {
        setContactName(value);
        return this;
    }

    @Override
    public LTentRecord value6(String value) {
        setMetadata(value);
        return this;
    }

    @Override
    public LTentRecord value7(Integer value) {
        setOrder(value);
        return this;
    }

    @Override
    public LTentRecord value8(String value) {
        setLocationId(value);
        return this;
    }

    @Override
    public LTentRecord value9(String value) {
        setYardId(value);
        return this;
    }

    @Override
    public LTentRecord value10(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public LTentRecord value11(String value) {
        setSigma(value);
        return this;
    }

    @Override
    public LTentRecord value12(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public LTentRecord value13(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public LTentRecord value14(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public LTentRecord value15(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public LTentRecord value16(String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public LTentRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Integer value7, String value8, String value9, Boolean value10, String value11, String value12, LocalDateTime value13, String value14, LocalDateTime value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ILTent from) {
        setKey(from.getKey());
        setName(from.getName());
        setCode(from.getCode());
        setContactPhone(from.getContactPhone());
        setContactName(from.getContactName());
        setMetadata(from.getMetadata());
        setOrder(from.getOrder());
        setLocationId(from.getLocationId());
        setYardId(from.getYardId());
        setActive(from.getActive());
        setSigma(from.getSigma());
        setLanguage(from.getLanguage());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    @Override
    public <E extends ILTent> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LTentRecord
     */
    public LTentRecord() {
        super(LTent.L_TENT);
    }

    /**
     * Create a detached, initialised LTentRecord
     */
    public LTentRecord(String key, String name, String code, String contactPhone, String contactName, String metadata, Integer order, String locationId, String yardId, Boolean active, String sigma, String language, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy) {
        super(LTent.L_TENT);

        setKey(key);
        setName(name);
        setCode(code);
        setContactPhone(contactPhone);
        setContactName(contactName);
        setMetadata(metadata);
        setOrder(order);
        setLocationId(locationId);
        setYardId(yardId);
        setActive(active);
        setSigma(sigma);
        setLanguage(language);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
    }

    /**
     * Create a detached, initialised LTentRecord
     */
    public LTentRecord(cn.vertxup.lbs.domain.tables.pojos.LTent value) {
        super(LTent.L_TENT);

        if (value != null) {
            setKey(value.getKey());
            setName(value.getName());
            setCode(value.getCode());
            setContactPhone(value.getContactPhone());
            setContactName(value.getContactName());
            setMetadata(value.getMetadata());
            setOrder(value.getOrder());
            setLocationId(value.getLocationId());
            setYardId(value.getYardId());
            setActive(value.getActive());
            setSigma(value.getSigma());
            setLanguage(value.getLanguage());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdatedAt(value.getUpdatedAt());
            setUpdatedBy(value.getUpdatedBy());
        }
    }

        public LTentRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
