/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.ambient.domain.tables.pojos;


import cn.vertxup.ambient.domain.tables.interfaces.IXAttachment;

import javax.annotation.Generated;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class XAttachment implements IXAttachment {

    private static final long serialVersionUID = 550831645;

    private String key;
    private String storeWay;
    private String status;
    private String name;
    private String fileName;
    private String fileKey;
    private String fileUrl;
    private String filePath;
    private String extension;
    private String module;
    private String mime;
    private Integer size;
    private Boolean active;
    private String sigma;
    private String metadata;
    private String language;
    private LocalDateTime createdAt;
    private String createdBy;
    private LocalDateTime updatedAt;
    private String updatedBy;

    public XAttachment() {
    }

    public XAttachment(XAttachment value) {
        this.key = value.key;
        this.storeWay = value.storeWay;
        this.status = value.status;
        this.name = value.name;
        this.fileName = value.fileName;
        this.fileKey = value.fileKey;
        this.fileUrl = value.fileUrl;
        this.filePath = value.filePath;
        this.extension = value.extension;
        this.module = value.module;
        this.mime = value.mime;
        this.size = value.size;
        this.active = value.active;
        this.sigma = value.sigma;
        this.metadata = value.metadata;
        this.language = value.language;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
        this.updatedAt = value.updatedAt;
        this.updatedBy = value.updatedBy;
    }

    public XAttachment(
        String key,
        String storeWay,
        String status,
        String name,
        String fileName,
        String fileKey,
        String fileUrl,
        String filePath,
        String extension,
        String module,
        String mime,
        Integer size,
        Boolean active,
        String sigma,
        String metadata,
        String language,
        LocalDateTime createdAt,
        String createdBy,
        LocalDateTime updatedAt,
        String updatedBy
    ) {
        this.key = key;
        this.storeWay = storeWay;
        this.status = status;
        this.name = name;
        this.fileName = fileName;
        this.fileKey = fileKey;
        this.fileUrl = fileUrl;
        this.filePath = filePath;
        this.extension = extension;
        this.module = module;
        this.mime = mime;
        this.size = size;
        this.active = active;
        this.sigma = sigma;
        this.metadata = metadata;
        this.language = language;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
    }

    public XAttachment(io.vertx.core.json.JsonObject json) {
        fromJson(json);
    }

    @Override
    public String getKey() {
        return this.key;
    }

    @Override
    public XAttachment setKey(String key) {
        this.key = key;
        return this;
    }

    @Override
    public String getStoreWay() {
        return this.storeWay;
    }

    @Override
    public XAttachment setStoreWay(String storeWay) {
        this.storeWay = storeWay;
        return this;
    }

    @Override
    public String getStatus() {
        return this.status;
    }

    @Override
    public XAttachment setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public XAttachment setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getFileName() {
        return this.fileName;
    }

    @Override
    public XAttachment setFileName(String fileName) {
        this.fileName = fileName;
        return this;
    }

    @Override
    public String getFileKey() {
        return this.fileKey;
    }

    @Override
    public XAttachment setFileKey(String fileKey) {
        this.fileKey = fileKey;
        return this;
    }

    @Override
    public String getFileUrl() {
        return this.fileUrl;
    }

    @Override
    public XAttachment setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
        return this;
    }

    @Override
    public String getFilePath() {
        return this.filePath;
    }

    @Override
    public XAttachment setFilePath(String filePath) {
        this.filePath = filePath;
        return this;
    }

    @Override
    public String getExtension() {
        return this.extension;
    }

    @Override
    public XAttachment setExtension(String extension) {
        this.extension = extension;
        return this;
    }

    @Override
    public String getModule() {
        return this.module;
    }

    @Override
    public XAttachment setModule(String module) {
        this.module = module;
        return this;
    }

    @Override
    public String getMime() {
        return this.mime;
    }

    @Override
    public XAttachment setMime(String mime) {
        this.mime = mime;
        return this;
    }

    @Override
    public Integer getSize() {
        return this.size;
    }

    @Override
    public XAttachment setSize(Integer size) {
        this.size = size;
        return this;
    }

    @Override
    public Boolean getActive() {
        return this.active;
    }

    @Override
    public XAttachment setActive(Boolean active) {
        this.active = active;
        return this;
    }

    @Override
    public String getSigma() {
        return this.sigma;
    }

    @Override
    public XAttachment setSigma(String sigma) {
        this.sigma = sigma;
        return this;
    }

    @Override
    public String getMetadata() {
        return this.metadata;
    }

    @Override
    public XAttachment setMetadata(String metadata) {
        this.metadata = metadata;
        return this;
    }

    @Override
    public String getLanguage() {
        return this.language;
    }

    @Override
    public XAttachment setLanguage(String language) {
        this.language = language;
        return this;
    }

    @Override
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public XAttachment setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    @Override
    public XAttachment setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    @Override
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public XAttachment setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    @Override
    public XAttachment setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("XAttachment (");

        sb.append(key);
        sb.append(", ").append(storeWay);
        sb.append(", ").append(status);
        sb.append(", ").append(name);
        sb.append(", ").append(fileName);
        sb.append(", ").append(fileKey);
        sb.append(", ").append(fileUrl);
        sb.append(", ").append(filePath);
        sb.append(", ").append(extension);
        sb.append(", ").append(module);
        sb.append(", ").append(mime);
        sb.append(", ").append(size);
        sb.append(", ").append(active);
        sb.append(", ").append(sigma);
        sb.append(", ").append(metadata);
        sb.append(", ").append(language);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(updatedBy);

        sb.append(")");
        return sb.toString();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IXAttachment from) {
        setKey(from.getKey());
        setStoreWay(from.getStoreWay());
        setStatus(from.getStatus());
        setName(from.getName());
        setFileName(from.getFileName());
        setFileKey(from.getFileKey());
        setFileUrl(from.getFileUrl());
        setFilePath(from.getFilePath());
        setExtension(from.getExtension());
        setModule(from.getModule());
        setMime(from.getMime());
        setSize(from.getSize());
        setActive(from.getActive());
        setSigma(from.getSigma());
        setMetadata(from.getMetadata());
        setLanguage(from.getLanguage());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IXAttachment> E into(E into) {
        into.from(this);
        return into;
    }
}
