/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.fm.domain.tables.records;


import cn.vertxup.fm.domain.tables.FDebtItem;
import cn.vertxup.fm.domain.tables.interfaces.IFDebtItem;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FDebtItemRecord extends UpdatableRecordImpl<FDebtItemRecord> implements VertxPojo, Record15<String, String, String, String, BigDecimal, String, String, String, String, Boolean, String, LocalDateTime, String, LocalDateTime, String>, IFDebtItem {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.KEY</code>. 「key」- 收款明细账单主键ID
     */
    @Override
    public FDebtItemRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.KEY</code>. 「key」- 收款明细账单主键ID
     */
    @Override
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.NAME</code>. 「name」 - 收款明细单标题
     */
    @Override
    public FDebtItemRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.NAME</code>. 「name」 - 收款明细单标题
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.CODE</code>. 「code」 - 收款明细单编号
     */
    @Override
    public FDebtItemRecord setCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.CODE</code>. 「code」 - 收款明细单编号
     */
    @Override
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.SERIAL</code>. 「serial」 - 收款明细单据号
     */
    @Override
    public FDebtItemRecord setSerial(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.SERIAL</code>. 「serial」 - 收款明细单据号
     */
    @Override
    public String getSerial() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.AMOUNT</code>.
     * 「amount」——价税合计，所有明细对应的实际结算金额
     */
    @Override
    public FDebtItemRecord setAmount(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.AMOUNT</code>.
     * 「amount」——价税合计，所有明细对应的实际结算金额
     */
    @Override
    public BigDecimal getAmount() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.DEBT_ID</code>. 「debtId」应收账单ID
     */
    @Override
    public FDebtItemRecord setDebtId(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.DEBT_ID</code>. 「debtId」应收账单ID
     */
    @Override
    public String getDebtId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.PAYMENT_ID</code>.
     * 「paymentId」收款单ID
     */
    @Override
    public FDebtItemRecord setPaymentId(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.PAYMENT_ID</code>.
     * 「paymentId」收款单ID
     */
    @Override
    public String getPaymentId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.SIGMA</code>. 「sigma」- 统一标识
     */
    @Override
    public FDebtItemRecord setSigma(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.SIGMA</code>. 「sigma」- 统一标识
     */
    @Override
    public String getSigma() {
        return (String) get(7);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.LANGUAGE</code>. 「language」-
     * 使用的语言
     */
    @Override
    public FDebtItemRecord setLanguage(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.LANGUAGE</code>. 「language」-
     * 使用的语言
     */
    @Override
    public String getLanguage() {
        return (String) get(8);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public FDebtItemRecord setActive(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.METADATA</code>. 「metadata」-
     * 附加配置数据
     */
    @Override
    public FDebtItemRecord setMetadata(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.METADATA</code>. 「metadata」-
     * 附加配置数据
     */
    @Override
    public String getMetadata() {
        return (String) get(10);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.CREATED_AT</code>. 「createdAt」-
     * 创建时间
     */
    @Override
    public FDebtItemRecord setCreatedAt(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.CREATED_AT</code>. 「createdAt」-
     * 创建时间
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.CREATED_BY</code>. 「createdBy」-
     * 创建人
     */
    @Override
    public FDebtItemRecord setCreatedBy(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.CREATED_BY</code>. 「createdBy」-
     * 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(12);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.UPDATED_AT</code>. 「updatedAt」-
     * 更新时间
     */
    @Override
    public FDebtItemRecord setUpdatedAt(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.UPDATED_AT</code>. 「updatedAt」-
     * 更新时间
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>DB_ETERNAL.F_DEBT_ITEM.UPDATED_BY</code>. 「updatedBy」-
     * 更新人
     */
    @Override
    public FDebtItemRecord setUpdatedBy(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.F_DEBT_ITEM.UPDATED_BY</code>. 「updatedBy」-
     * 更新人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<String, String, String, String, BigDecimal, String, String, String, String, Boolean, String, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<String, String, String, String, BigDecimal, String, String, String, String, Boolean, String, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return FDebtItem.F_DEBT_ITEM.KEY;
    }

    @Override
    public Field<String> field2() {
        return FDebtItem.F_DEBT_ITEM.NAME;
    }

    @Override
    public Field<String> field3() {
        return FDebtItem.F_DEBT_ITEM.CODE;
    }

    @Override
    public Field<String> field4() {
        return FDebtItem.F_DEBT_ITEM.SERIAL;
    }

    @Override
    public Field<BigDecimal> field5() {
        return FDebtItem.F_DEBT_ITEM.AMOUNT;
    }

    @Override
    public Field<String> field6() {
        return FDebtItem.F_DEBT_ITEM.DEBT_ID;
    }

    @Override
    public Field<String> field7() {
        return FDebtItem.F_DEBT_ITEM.PAYMENT_ID;
    }

    @Override
    public Field<String> field8() {
        return FDebtItem.F_DEBT_ITEM.SIGMA;
    }

    @Override
    public Field<String> field9() {
        return FDebtItem.F_DEBT_ITEM.LANGUAGE;
    }

    @Override
    public Field<Boolean> field10() {
        return FDebtItem.F_DEBT_ITEM.ACTIVE;
    }

    @Override
    public Field<String> field11() {
        return FDebtItem.F_DEBT_ITEM.METADATA;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return FDebtItem.F_DEBT_ITEM.CREATED_AT;
    }

    @Override
    public Field<String> field13() {
        return FDebtItem.F_DEBT_ITEM.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return FDebtItem.F_DEBT_ITEM.UPDATED_AT;
    }

    @Override
    public Field<String> field15() {
        return FDebtItem.F_DEBT_ITEM.UPDATED_BY;
    }

    @Override
    public String component1() {
        return getKey();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getCode();
    }

    @Override
    public String component4() {
        return getSerial();
    }

    @Override
    public BigDecimal component5() {
        return getAmount();
    }

    @Override
    public String component6() {
        return getDebtId();
    }

    @Override
    public String component7() {
        return getPaymentId();
    }

    @Override
    public String component8() {
        return getSigma();
    }

    @Override
    public String component9() {
        return getLanguage();
    }

    @Override
    public Boolean component10() {
        return getActive();
    }

    @Override
    public String component11() {
        return getMetadata();
    }

    @Override
    public LocalDateTime component12() {
        return getCreatedAt();
    }

    @Override
    public String component13() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component14() {
        return getUpdatedAt();
    }

    @Override
    public String component15() {
        return getUpdatedBy();
    }

    @Override
    public String value1() {
        return getKey();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getCode();
    }

    @Override
    public String value4() {
        return getSerial();
    }

    @Override
    public BigDecimal value5() {
        return getAmount();
    }

    @Override
    public String value6() {
        return getDebtId();
    }

    @Override
    public String value7() {
        return getPaymentId();
    }

    @Override
    public String value8() {
        return getSigma();
    }

    @Override
    public String value9() {
        return getLanguage();
    }

    @Override
    public Boolean value10() {
        return getActive();
    }

    @Override
    public String value11() {
        return getMetadata();
    }

    @Override
    public LocalDateTime value12() {
        return getCreatedAt();
    }

    @Override
    public String value13() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value14() {
        return getUpdatedAt();
    }

    @Override
    public String value15() {
        return getUpdatedBy();
    }

    @Override
    public FDebtItemRecord value1(String value) {
        setKey(value);
        return this;
    }

    @Override
    public FDebtItemRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public FDebtItemRecord value3(String value) {
        setCode(value);
        return this;
    }

    @Override
    public FDebtItemRecord value4(String value) {
        setSerial(value);
        return this;
    }

    @Override
    public FDebtItemRecord value5(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public FDebtItemRecord value6(String value) {
        setDebtId(value);
        return this;
    }

    @Override
    public FDebtItemRecord value7(String value) {
        setPaymentId(value);
        return this;
    }

    @Override
    public FDebtItemRecord value8(String value) {
        setSigma(value);
        return this;
    }

    @Override
    public FDebtItemRecord value9(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public FDebtItemRecord value10(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public FDebtItemRecord value11(String value) {
        setMetadata(value);
        return this;
    }

    @Override
    public FDebtItemRecord value12(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FDebtItemRecord value13(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public FDebtItemRecord value14(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FDebtItemRecord value15(String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public FDebtItemRecord values(String value1, String value2, String value3, String value4, BigDecimal value5, String value6, String value7, String value8, String value9, Boolean value10, String value11, LocalDateTime value12, String value13, LocalDateTime value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IFDebtItem from) {
        setKey(from.getKey());
        setName(from.getName());
        setCode(from.getCode());
        setSerial(from.getSerial());
        setAmount(from.getAmount());
        setDebtId(from.getDebtId());
        setPaymentId(from.getPaymentId());
        setSigma(from.getSigma());
        setLanguage(from.getLanguage());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    @Override
    public <E extends IFDebtItem> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FDebtItemRecord
     */
    public FDebtItemRecord() {
        super(FDebtItem.F_DEBT_ITEM);
    }

    /**
     * Create a detached, initialised FDebtItemRecord
     */
    public FDebtItemRecord(String key, String name, String code, String serial, BigDecimal amount, String debtId, String paymentId, String sigma, String language, Boolean active, String metadata, LocalDateTime createdAt, String createdBy, LocalDateTime updatedAt, String updatedBy) {
        super(FDebtItem.F_DEBT_ITEM);

        setKey(key);
        setName(name);
        setCode(code);
        setSerial(serial);
        setAmount(amount);
        setDebtId(debtId);
        setPaymentId(paymentId);
        setSigma(sigma);
        setLanguage(language);
        setActive(active);
        setMetadata(metadata);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
    }

    /**
     * Create a detached, initialised FDebtItemRecord
     */
    public FDebtItemRecord(cn.vertxup.fm.domain.tables.pojos.FDebtItem value) {
        super(FDebtItem.F_DEBT_ITEM);

        if (value != null) {
            setKey(value.getKey());
            setName(value.getName());
            setCode(value.getCode());
            setSerial(value.getSerial());
            setAmount(value.getAmount());
            setDebtId(value.getDebtId());
            setPaymentId(value.getPaymentId());
            setSigma(value.getSigma());
            setLanguage(value.getLanguage());
            setActive(value.getActive());
            setMetadata(value.getMetadata());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdatedAt(value.getUpdatedAt());
            setUpdatedBy(value.getUpdatedBy());
        }
    }

        public FDebtItemRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
