/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.lbs.domain.tables.pojos;


import cn.vertxup.lbs.domain.tables.interfaces.ILState;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.time.LocalDateTime;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LState implements VertxPojo, ILState {

    private static final long serialVersionUID = 1L;

    private String        key;
    private String        name;
    private String        code;
    private String        alias;
    private String        metadata;
    private Integer       order;
    private String        countryId;
    private Boolean       active;
    private String        sigma;
    private String        language;
    private LocalDateTime createdAt;
    private String        createdBy;
    private LocalDateTime updatedAt;
    private String        updatedBy;

    public LState() {}

    public LState(ILState value) {
        this.key = value.getKey();
        this.name = value.getName();
        this.code = value.getCode();
        this.alias = value.getAlias();
        this.metadata = value.getMetadata();
        this.order = value.getOrder();
        this.countryId = value.getCountryId();
        this.active = value.getActive();
        this.sigma = value.getSigma();
        this.language = value.getLanguage();
        this.createdAt = value.getCreatedAt();
        this.createdBy = value.getCreatedBy();
        this.updatedAt = value.getUpdatedAt();
        this.updatedBy = value.getUpdatedBy();
    }

    public LState(
        String        key,
        String        name,
        String        code,
        String        alias,
        String        metadata,
        Integer       order,
        String        countryId,
        Boolean       active,
        String        sigma,
        String        language,
        LocalDateTime createdAt,
        String        createdBy,
        LocalDateTime updatedAt,
        String        updatedBy
    ) {
        this.key = key;
        this.name = name;
        this.code = code;
        this.alias = alias;
        this.metadata = metadata;
        this.order = order;
        this.countryId = countryId;
        this.active = active;
        this.sigma = sigma;
        this.language = language;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
    }

        public LState(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.KEY</code>. 「key」- 省会主键
     */
    @Override
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.KEY</code>. 「key」- 省会主键
     */
    @Override
    public LState setKey(String key) {
        this.key = key;
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.NAME</code>. 「name」- 省会名称
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.NAME</code>. 「name」- 省会名称
     */
    @Override
    public LState setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.CODE</code>. 「code」- 省会编码
     */
    @Override
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.CODE</code>. 「code」- 省会编码
     */
    @Override
    public LState setCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.ALIAS</code>. 「alias」- 别名（缩写）
     */
    @Override
    public String getAlias() {
        return this.alias;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.ALIAS</code>. 「alias」- 别名（缩写）
     */
    @Override
    public LState setAlias(String alias) {
        this.alias = alias;
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.METADATA</code>. 「metadata」- 附加配置
     */
    @Override
    public String getMetadata() {
        return this.metadata;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.METADATA</code>. 「metadata」- 附加配置
     */
    @Override
    public LState setMetadata(String metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.ORDER</code>. 「order」- 排序
     */
    @Override
    public Integer getOrder() {
        return this.order;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.ORDER</code>. 「order」- 排序
     */
    @Override
    public LState setOrder(Integer order) {
        this.order = order;
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.COUNTRY_ID</code>. 「countryId」- 国家ID
     */
    @Override
    public String getCountryId() {
        return this.countryId;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.COUNTRY_ID</code>. 「countryId」- 国家ID
     */
    @Override
    public LState setCountryId(String countryId) {
        this.countryId = countryId;
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return this.active;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public LState setActive(Boolean active) {
        this.active = active;
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.SIGMA</code>. 「sigma」- 统一标识
     */
    @Override
    public String getSigma() {
        return this.sigma;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.SIGMA</code>. 「sigma」- 统一标识
     */
    @Override
    public LState setSigma(String sigma) {
        this.sigma = sigma;
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public String getLanguage() {
        return this.language;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public LState setLanguage(String language) {
        this.language = language;
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.CREATED_AT</code>. 「createdAt」- 创建时间
     */
    @Override
    public LState setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.CREATED_BY</code>. 「createdBy」- 创建人
     */
    @Override
    public LState setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.UPDATED_AT</code>. 「updatedAt」- 更新时间
     */
    @Override
    public LState setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Getter for <code>DB_ETERNAL.L_STATE.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for <code>DB_ETERNAL.L_STATE.UPDATED_BY</code>. 「updatedBy」- 更新人
     */
    @Override
    public LState setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LState (");

        sb.append(key);
        sb.append(", ").append(name);
        sb.append(", ").append(code);
        sb.append(", ").append(alias);
        sb.append(", ").append(metadata);
        sb.append(", ").append(order);
        sb.append(", ").append(countryId);
        sb.append(", ").append(active);
        sb.append(", ").append(sigma);
        sb.append(", ").append(language);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(updatedBy);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ILState from) {
        setKey(from.getKey());
        setName(from.getName());
        setCode(from.getCode());
        setAlias(from.getAlias());
        setMetadata(from.getMetadata());
        setOrder(from.getOrder());
        setCountryId(from.getCountryId());
        setActive(from.getActive());
        setSigma(from.getSigma());
        setLanguage(from.getLanguage());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    @Override
    public <E extends ILState> E into(E into) {
        into.from(this);
        return into;
    }
}
