SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
-- 删除原来的数据库
DROP DATABASE IF EXISTS DB_ORIGIN_X;
CREATE DATABASE IF NOT EXISTS DB_ORIGIN_X DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- 业务数据库 DB_IOP
DROP DATABASE IF EXISTS DB_IOP;
CREATE DATABASE IF NOT EXISTS DB_IOP DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- 历史数据库 DB_IOP_HIS
DROP DATABASE IF EXISTS DB_IOP_HIS;
CREATE DATABASE IF NOT EXISTS DB_IOP_HIS DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_bin;